name: C/C++ CI

on:
  release:
  push:
  pull_request:
    branches:
    - master
  schedule:
    - cron: 0 6 * * *

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
        cc: [gcc-8]
        cxx: [g++-8]
        include:
        - os: macOS-latest
          cc: clang
          cxx: n/a
        - os: windows-latest
          cc: msvc
          cxx: n/a
        - os: ubuntu-18.04
          cc: gcc-5
          cxx: g++-5
        - os: ubuntu-18.04
          cc: gcc-6
          cxx: g++-6
        - os: ubuntu-18.04
          cc: gcc-7
          cxx: g++-7
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: Install PPA's (linux)
      run:  sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      if: runner.os == 'Linux'
    - name: Install libraries (linux)
      run: sudo apt-get install -yqq ${{ matrix.cc }} ${{ matrix.cxx }} libstdc++6 build-essential git curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libjack-jackd2-dev
      if: runner.os == 'Linux'
    - name: fetch submodules
      run: git submodule update --init --recursive
    - name: make dependencies (linux)
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: make dep -j4
      if: runner.os == 'Linux'
    - name: compile (linux)
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: make -j4
      if: runner.os == 'Linux'
    - uses: actions/upload-artifact@v2
      with:
        name: build-folder-ubuntu-18.04
        path: build
      if: runner.os == 'Linux' && matrix.cc == 'gcc-8' && matrix.os == 'ubuntu-18.04'
    - name: make dependencies (mac)
      run: make dep -j4
      if: runner.os == 'macOS'
    - name: compile (mac)
      run: make -j4
      if: runner.os == 'macOS'
    - uses: actions/upload-artifact@v2
      with:
        name: build-folder-mac
        path: build
      if: runner.os == 'macOS'
    - uses: numworks/setup-msys2@v1
      with:
        path-type: inherit
        update: true
      if: runner.os == 'Windows'
    - name: Setup msys minggw (windows)
      run: msys2do makepkg-mingw -sCLfc --noconfirm
      if: runner.os == 'Windows'
    - name: Install libraries (windows)
      run: msys2do pacman --noconfirm -Su git wget make tar unzip zip mingw-w64-x86_64-gcc mingw-w64-x86_64-gdb mingw-w64-x86_64-cmake autoconf automake mingw-w64-x86_64-libtool mingw-w64-x86_64-jq python
      if: runner.os == 'Windows'
    - name: make dependencies (windows)
      run: msys2do make dep -j4
      if: runner.os == 'Windows'
    - name: compile (windows)
      run: msys2do make -j4
      if: runner.os == 'Windows'
    - uses: actions/upload-artifact@v2
      with:
        name: build-folder-win
        path: build
      if: runner.os == 'Windows'
