name: C/C++ CI

on:
  release:
  push:
  pull_request:
    branches:
    - master
  schedule:
    - cron: 0 6 1 * *

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
        cc: [gcc-8]
        cxx: [g++-8]
        experimental: [true]
        include:
        - os: macOS-latest
          cc: clang
          cxx: clang++
          experimental: true
        - os: windows-latest
          cc: msvc
          cxx: n/a
          experimental: true
        - os: ubuntu-18.04
          cc: gcc-5
          cxx: g++-5
          experimental: true
        - os: ubuntu-18.04
          cc: gcc-6
          cxx: g++-6
          experimental: true
        - os: ubuntu-18.04
          cc: gcc-7
          cxx: g++-7
          experimental: true
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: fetch submodules
      run: git submodule update --init --recursive
    - name: clone fundamental plugins
      run: cd plugins && git clone https://github.com/VCVRack/Fundamental.git && cd Fundamental && git checkout v0.6 && git submodule update --init --recursive && cd ../..
    - name: clone bridge (0.6x only)
      run: git clone https://github.com/Lewiscowles1986/Bridge.git && cd Bridge && git checkout v0.6 && git submodule update --init --recursive && cd ../
    - name: Install PPA's (linux)
      run:  sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      if: runner.os == 'Linux'
    - name: Install libraries (linux)
      run: sudo apt-get install -yqq ${{ matrix.cc }} ${{ matrix.cxx }} libstdc++6 build-essential git gdb curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libjack-jackd2-dev jq openssl
      if: runner.os == 'Linux'
    - name: install openSSL (windows)
      run: choco install openssl
      if: runner.os == 'Windows'
    - name: install openSSL (mac)
      run: brew update && brew install openssl@1.1 && brew install llvm
      if: runner.os == 'macOS'
    - name: decrypt VTSDK (linux, mac)
      env:
        VSTSDK_KEY: ${{ secrets.vst_sdk_enckey }}
      run: openssl aes-256-cbc -d -md sha512 -in vendor/vstsdk.zip.enc -out vendor/vstsdk.zip -pass pass:$VSTSDK_KEY
      if: runner.os != 'Windows'
    - name: decrypt CoreAudio SDK (mac)
      env:
        CORE_AUDIO_SDK_KEY: ${{ secrets.core_audio_sdk_enckey }}
      run: openssl aes-256-cbc -d -md sha512 -in vendor/CoreAudio2.zip.enc -out vendor/CoreAudio.zip -pass pass:$CORE_AUDIO_SDK_KEY
      if: runner.os == 'macOS'
    - name: make dependencies (linux, mac)
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: make dep -j4
      if: runner.os != 'Windows'
    - name: compile core (linux, mac)
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: make -j4
      if: runner.os != 'Windows'
    - name: compile fundamental plugins (linux, mac)
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: cd plugins/Fundamental && make dep -j4 && make -j4 && cd ../..
      if: runner.os != 'Windows'
    - name: build VST bridge (linux, osx)
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: cd Bridge/VST && unzip ../../vendor/vstsdk.zip -d . && mv vstsdk2.4 VST2_SDK && make dist && FX=1 make dist && cd ../..
      if: runner.os != 'Windows' 
    - name: build package (Linux)
      run: make dist
      if: runner.os == 'Linux'
    - uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: dist/Rack-*.zip
      if: runner.os == 'Linux' && matrix.cc == 'gcc-8' && matrix.os == 'ubuntu-18.04'
    - name: compile AU Apple Bridge (mac)
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: cd Bridge/AU && unzip ../../vendor/CoreAudio.zip -d . && mv CoreAudio2 CoreAudio && make dist && cd ../..
      if: runner.os == 'macOS'
    - name: build package (mac)
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: make dist
      if: runner.os == 'macOS'
    - uses: actions/upload-artifact@v2
      with:
        name: OSx
        path: dist/*.dmg
      if: runner.os == 'macOS'
    - uses: actions/upload-artifact@v2
      with:
        name: OSx
        path: dist/*.zip
      if: runner.os == 'macOS'
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        update: true
        install: >-
          git
          wget
          make
          tar
          unzip
          zip
          mingw-w64-i686-toolchain
          mingw-w64-i686-gcc
          mingw-w64-i686-gdb
          mingw-w64-i686-cmake
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gdb
          mingw-w64-x86_64-cmake
          autoconf
          automake
          mingw-w64-i686-libtool
          mingw-w64-i686-jq
          mingw-w64-x86_64-libtool
          mingw-w64-x86_64-jq
          python
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      if: runner.os == 'Windows'
    - name: Setup msys minggw (windows)
      shell: msys2 {0}
      run: updpkgsums && makepkg-mingw -sCLfc --noconfirm
      if: runner.os == 'Windows'
    - name: decrypt VTSDK (windows)
      run: openssl aes-256-cbc -d -md sha512 -in vendor/vstsdk.zip.enc -out vendor/vstsdk.zip -pass pass:${{ secrets.vst_sdk_enckey }}
      if: runner.os == 'Windows'
    - name: make dependencies (windows)
      run: make dep -j4
      if: runner.os == 'Windows'
    - name: compile (windows)
      run: make -j4
      if: runner.os == 'Windows'
    - name: compile all plugins (windows)
      run: cd plugins/Fundamental && make dep -j4 && make -j4 && cd ../..
      if: runner.os == 'Windows'
    - name: build VST bridge (windows)
      run: cd Bridge/VST && unzip ../../vendor/vstsdk.zip -d . && mv vstsdk2.4 VST2_SDK && make dist && FX=1 make dist && cd ../..
      if: runner.os == 'Windows' 
    - name: build package (windows)
      run: make dist
      if: runner.os == 'Windows'
    - uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: dist/*.exe
      if: runner.os == 'Windows'
    - uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: dist/*.zip
      if: runner.os == 'Windows'
